/** Auto-ported from QualifierController::qualifiercheckinengine */
export const DATA_QUALIFIERS_SELECT = `SELECT CONCAT('{',NULLIF(CONCAT_WS(',',CONCAT('"FuelTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FuelTypeID,0) ORDER BY IFNULL(a.FuelTypeID,0) SEPARATOR ','),']'),CONCAT('"AspirationID":[',GROUP_CONCAT(DISTINCT IFNULL(a.AspirationID,0) ORDER BY IFNULL(a.AspirationID,0) SEPARATOR ','),']'),CONCAT('"DriveTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.DriveTypeID,0) ORDER BY IFNULL(a.DriveTypeID,0) SEPARATOR ','),']'),CONCAT('"EngineVINID":[',GROUP_CONCAT(DISTINCT IFNULL(a.EngineVINID,0) ORDER BY IFNULL(a.EngineVINID,0) SEPARATOR ','),']'),CONCAT('"EngineDesignationID":[',GROUP_CONCAT(DISTINCT IFNULL(a.EngineDesignationID,0) ORDER BY IFNULL(a.EngineDesignationID,0) SEPARATOR ','),']'),CONCAT('"CylinderHeadTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.CylinderHeadTypeID,0) ORDER BY IFNULL(a.CylinderHeadTypeID,0) SEPARATOR ','),']'),CONCAT('"SubModelID":[',GROUP_CONCAT(DISTINCT IFNULL(a.SubModelID,0) ORDER BY IFNULL(a.SubModelID,0) SEPARATOR ','),']'),CONCAT('"TransmissionControlTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransmissionControlTypeID,0) ORDER BY IFNULL(a.TransmissionControlTypeID,0) SEPARATOR ','),']'),CONCAT('"TransmissionNumSpeedsID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransmissionNumSpeedsID,0) ORDER BY IFNULL(a.TransmissionNumSpeedsID,0) SEPARATOR ','),']'),CONCAT('"ValvesPerEngineID":[',GROUP_CONCAT(DISTINCT IFNULL(a.ValvesPerEngineID,0) ORDER BY IFNULL(a.ValvesPerEngineID,0) SEPARATOR ','),']'),CONCAT('"FuelDeliveryTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FuelDeliveryTypeID,0) ORDER BY IFNULL(a.FuelDeliveryTypeID,0) SEPARATOR ','),']'),CONCAT('"BedTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BedTypeID,0) ORDER BY IFNULL(a.BedTypeID,0) SEPARATOR ','),']'),CONCAT('"BodyNumDoorsID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BodyNumDoorsID,0) ORDER BY IFNULL(a.BodyNumDoorsID,0) SEPARATOR ','),']'),CONCAT('"EngineMfrID":[',GROUP_CONCAT(DISTINCT IFNULL(a.EngineMfrID,0) ORDER BY IFNULL(a.EngineMfrID,0) SEPARATOR ','),']'),CONCAT('"FuelDeliverySubTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FuelDeliverySubTypeID,0) ORDER BY IFNULL(a.FuelDeliverySubTypeID,0) SEPARATOR ','),']'),CONCAT('"FuelSystemControlTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FuelSystemControlTypeID,0) ORDER BY IFNULL(a.FuelSystemControlTypeID,0) SEPARATOR ','),']'),CONCAT('"FuelSystemDesignID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FuelSystemDesignID,0) ORDER BY IFNULL(a.FuelSystemDesignID,0) SEPARATOR ','),']'),CONCAT('"SteeringTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.SteeringTypeID,0) ORDER BY IFNULL(a.SteeringTypeID,0) SEPARATOR ','),']'),CONCAT('"TransmissionTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransmissionTypeID,0) ORDER BY IFNULL(a.TransmissionTypeID,0) SEPARATOR ','),']'),CONCAT('"BedLengthID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BedLengthID,0) ORDER BY IFNULL(a.BedLengthID,0) SEPARATOR ','),']'),CONCAT('"BodyTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BodyTypeID,0) ORDER BY IFNULL(a.BodyTypeID,0) SEPARATOR ','),']'),CONCAT('"BrakeABSID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BrakeABSID,0) ORDER BY IFNULL(a.BrakeABSID,0) SEPARATOR ','),']'),CONCAT('"BrakeSystemID":[',GROUP_CONCAT(DISTINCT IFNULL(a.BrakeSystemID,0) ORDER BY IFNULL(a.BrakeSystemID,0) SEPARATOR ','),']'),CONCAT('"EngineVersionID":[',GROUP_CONCAT(DISTINCT IFNULL(a.EngineVersionID,0) ORDER BY IFNULL(a.EngineVersionID,0) SEPARATOR ','),']'),CONCAT('"FrontBrakeTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FrontBrakeTypeID,0) ORDER BY IFNULL(a.FrontBrakeTypeID,0) SEPARATOR ','),']'),CONCAT('"FrontSpringTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.FrontSpringTypeID,0) ORDER BY IFNULL(a.FrontSpringTypeID,0) SEPARATOR ','),']'),CONCAT('"IgnitionSystemTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.IgnitionSystemTypeID,0) ORDER BY IFNULL(a.IgnitionSystemTypeID,0) SEPARATOR ','),']'),CONCAT('"MfrBodyCodeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.MfrBodyCodeID,0) ORDER BY IFNULL(a.MfrBodyCodeID,0) SEPARATOR ','),']'),CONCAT('"PowerOutputID":[',GROUP_CONCAT(DISTINCT IFNULL(a.PowerOutputID,0) ORDER BY IFNULL(a.PowerOutputID,0) SEPARATOR ','),']'),CONCAT('"RearBrakeTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.RearBrakeTypeID,0) ORDER BY IFNULL(a.RearBrakeTypeID,0) SEPARATOR ','),']'),CONCAT('"RearSpringTypeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.RearSpringTypeID,0) ORDER BY IFNULL(a.RearSpringTypeID,0) SEPARATOR ','),']'),CONCAT('"RegionID":[',GROUP_CONCAT(DISTINCT IFNULL(a.RegionID,0) ORDER BY IFNULL(a.RegionID,0) SEPARATOR ','),']'),CONCAT('"SteeringSystemID":[',GROUP_CONCAT(DISTINCT IFNULL(a.SteeringSystemID,0) ORDER BY IFNULL(a.SteeringSystemID,0) SEPARATOR ','),']'),CONCAT('"TransElecControlledID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransElecControlledID,0) ORDER BY IFNULL(a.TransElecControlledID,0) SEPARATOR ','),']'),CONCAT('"TransmissionMfrID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransmissionMfrID,0) ORDER BY IFNULL(a.TransmissionMfrID,0) SEPARATOR ','),']'),CONCAT('"TransmissionMfrCodeID":[',GROUP_CONCAT(DISTINCT IFNULL(a.TransmissionMfrCodeID,0) ORDER BY IFNULL(a.TransmissionMfrCodeID,0) SEPARATOR ','),']'),CONCAT('"WheelBaseID":[',GROUP_CONCAT(DISTINCT IFNULL(a.WheelBaseID,0) ORDER BY IFNULL(a.WheelBaseID,0) SEPARATOR ','),']'),CONCAT('"PositionID":[',GROUP_CONCAT(DISTINCT IFNULL(a.PositionID,0) ORDER BY IFNULL(a.PositionID,0) SEPARATOR ','),']')),''),'}') AS data_json`;

/** VCDB column used in WHERE when a qualifier is already selected */
export const QUALIFIER_MAIN_TABLE = {
  AspirationID: "aspiration.AspirationID",
  BedLengthID: "bedlength.BedLengthID",
  BedTypeID: "bedtype.BedTypeID",
  BodyNumDoorsID: "bodynumdoors.BodyNumDoorsID",
  BodyTypeID: "bodytype.BodyTypeID",
  BrakeABSID: "brakeabs.BrakeABSID",
  BrakeSystemID: "brakesystem.BrakeSystemID",
  CylinderHeadTypeID: "cylinderheadtype.CylinderHeadTypeID",
  DriveTypeID: "drivetype.DriveTypeID",
  EngineDesignationID: "enginedesignation.EngineDesignationID",
  EngineMfrID: "mfr.MfrID",
  EngineVersionID: "engineversion.EngineVersionID",
  EngineVINID: "enginevin.EngineVINID",
  FrontBrakeTypeID: "braketype_front.BrakeTypeID",
  FrontSpringTypeID: "springtype_front.SpringTypeID",
  FuelDeliverySubTypeID: "fueldeliverysubtype.FuelDeliverySubTypeID",
  FuelDeliveryTypeID: "fueldeliverytype.FuelDeliveryTypeID",
  FuelSystemControlTypeID: "fuelsystemcontroltype.FuelSystemControlTypeID",
  FuelSystemDesignID: "fuelsystemdesign.FuelSystemDesignID",
  FuelTypeID: "fueltype.FuelTypeID",
  IgnitionSystemTypeID: "ignitionsystemtype.IgnitionSystemTypeID",
  MfrBodyCodeID: "mfrbodycode.MfrBodyCodeID",
  PowerOutputID: "poweroutput.PowerOutputID",
  RearBrakeTypeID: "braketype_rear.BrakeTypeID",
  RearSpringTypeID: "springtype_rear.SpringTypeID",
  RegionID: "region.RegionID",
  SteeringSystemID: "steeringsystem.SteeringSystemID",
  SteeringTypeID: "steeringtype.SteeringTypeID",
  SubModelID: "submodel.SubModelID",
  TransElecControlledID: "eleccontrolled.ElecControlledID",
  TransmissionControlTypeID: "transmissioncontroltype.TransmissionControlTypeID",
  TransmissionMfrCodeID: "transmissionmfrcode.TransmissionMfrCodeID",
  TransmissionMfrID: "mfr.MfrID",
  TransmissionNumSpeedsID: "transmissionnumspeeds.TransmissionNumSpeedsID",
  TransmissionTypeID: "transmissiontype.TransmissionTypeID",
  ValvesPerEngineID: "valves.ValvesID",
  WheelBaseID: "wheelbase.WheelBaseID",
};

export const QUALIFIER_COLUMNS = Object.keys(QUALIFIER_MAIN_TABLE);

export const VEHICLE_DEFINITION = {
  AspirationID: "Aspiration",
  BedLengthID: "Bed Length",
  BedTypeID: "Bed Type",
  BodyNumDoorsID: "Number of Doors",
  BodyTypeID: "Body Type",
  BrakeABSID: "ABS Type",
  BrakeSystemID: "Brake System",
  CylinderHeadTypeID: "Cylinder Head",
  DriveTypeID: "Drive Type",
  EngineDesignationID: "Engine Design",
  EngineMfrID: "Engine Mfr",
  EngineVersionID: "Engine Version",
  EngineVINID: "VIN",
  FrontBrakeTypeID: "Front Brake",
  FrontSpringTypeID: "Front Spring",
  FuelDeliverySubTypeID: "Fuel Del. Sub Type",
  FuelDeliveryTypeID: "Fuel Del. Type",
  FuelSystemControlTypeID: "Fuel Sys. Control",
  FuelSystemDesignID: "Fuel Sys. Design",
  FuelTypeID: "Fuel",
  IgnitionSystemTypeID: "Ignition",
  MfrBodyCodeID: "Body Code",
  PowerOutputID: "Power Output",
  RearBrakeTypeID: "Rear Brake",
  RearSpringTypeID: "Rear Spring",
  RegionID: "Region",
  SteeringSystemID: "Steering System",
  SteeringTypeID: "Steering",
  SubModelID: "SubModel",
  TransElecControlledID: "Trans Elec Ctrl",
  TransmissionControlTypeID: "Trans Ctrl Type",
  TransmissionMfrCodeID: "Trans Mfr Code",
  TransmissionMfrID: "Transmission Mfr",
  TransmissionNumSpeedsID: "Trans Num Speeds",
  TransmissionTypeID: "Trans Type",
  ValvesPerEngineID: "Valves Per Engine",
  WheelBaseID: "Wheel Base",
};

export const VCDB_TABLE_JOINS = {
  "basevehicle": "LEFT JOIN basevehicle ON vehicle.BaseVehicleID = basevehicle.BaseVehicleID",
  "region": "LEFT JOIN region ON vehicle.RegionID = region.RegionID",
  "submodel": "LEFT JOIN submodel ON vehicle.SubmodelID = submodel.SubModelID",
  "vehicletospringtypeconfig": "LEFT JOIN vehicletospringtypeconfig ON vehicle.VehicleID = vehicletospringtypeconfig.VehicleID",
  "springtype_front": "LEFT JOIN springtypeconfig ON vehicletospringtypeconfig.SpringTypeConfigID = springtypeconfig.SpringTypeConfigID",
  "springtype": "LEFT JOIN springtype springtype_front ON springtypeconfig.FrontSpringTypeID = springtype_front.SpringTypeID",
  "springtype_rear": "LEFT JOIN springtype springtype_rear ON springtypeconfig.RearSpringTypeID = springtype_rear.SpringTypeID",
  "vehicletosteeringconfig": "LEFT JOIN vehicletosteeringconfig ON vehicle.VehicleID = vehicletosteeringconfig.VehicleID",
  "steeringconfig": "LEFT JOIN steeringconfig ON vehicletosteeringconfig.SteeringConfigID = steeringconfig.SteeringConfigID",
  "steeringtype": "LEFT JOIN steeringtype ON steeringconfig.SteeringTypeID = steeringtype.SteeringTypeID",
  "steeringsystem": "LEFT JOIN steeringsystem ON steeringconfig.SteeringSystemID = steeringsystem.SteeringSystemID",
  "vehicletobedconfig": "LEFT JOIN vehicletobedconfig ON vehicle.VehicleID = vehicletobedconfig.VehicleID",
  "bedconfig": "LEFT JOIN bedconfig ON vehicletobedconfig.BedConfigID = bedconfig.BedConfigID",
  "bedtype": "LEFT JOIN bedtype ON bedconfig.BedTypeID = bedtype.BedTypeID",
  "bedlength": "LEFT JOIN bedlength ON bedconfig.BedLengthID = bedlength.BedLengthID",
  "vehicletobrakeconfig": "LEFT JOIN vehicletobrakeconfig ON vehicle.VehicleID = vehicletobrakeconfig.VehicleID",
  "braketype_front": "LEFT JOIN brakeconfig ON vehicletobrakeconfig.BrakeConfigID = brakeconfig.BrakeConfigID",
  "braketype": "LEFT JOIN braketype braketype_front ON brakeconfig.FrontBrakeTypeID = braketype_front.BrakeTypeID",
  "braketype_rear": "LEFT JOIN braketype braketype_rear ON brakeconfig.RearBrakeTypeID = braketype_rear.BrakeTypeID",
  "brakeabs": "LEFT JOIN brakeabs ON brakeconfig.BrakeABSID = brakeabs.BrakeABSID",
  "brakesystem": "LEFT JOIN brakesystem ON brakeconfig.BrakeSystemID = brakesystem.BrakeSystemID",
  "vehicletodrivetype": "LEFT JOIN vehicletodrivetype ON vehicle.VehicleID = vehicletodrivetype.VehicleID",
  "drivetype": "LEFT JOIN drivetype ON vehicletodrivetype.DriveTypeID = drivetype.DriveTypeID",
  "vehicletowheelbase": "LEFT JOIN vehicletowheelbase ON vehicle.VehicleID = vehicletowheelbase.VehicleID",
  "wheelbase": "LEFT JOIN wheelbase ON vehicletowheelbase.WheelbaseID = wheelbase.WheelBaseID",
  "vehicletobodystyleconfig": "LEFT JOIN vehicletobodystyleconfig ON vehicle.VehicleID = vehicletobodystyleconfig.VehicleID",
  "bodystyleconfig": "LEFT JOIN bodystyleconfig ON vehicletobodystyleconfig.BodyStyleConfigID = bodystyleconfig.BodyStyleConfigID",
  "bodynumdoors": "LEFT JOIN bodynumdoors ON bodystyleconfig.BodyNumDoorsID = bodynumdoors.BodyNumDoorsID",
  "bodytype": "LEFT JOIN bodytype ON bodystyleconfig.BodyTypeID = bodytype.BodyTypeID",
  "vehicletomfrbodycode": "LEFT JOIN vehicletomfrbodycode ON vehicle.VehicleID = vehicletomfrbodycode.VehicleID",
  "mfrbodycode": "LEFT JOIN mfrbodycode ON vehicletomfrbodycode.MfrBodyCodeID = mfrbodycode.MfrBodyCodeID",
  "vehicletotransmission": "LEFT JOIN vehicletotransmission ON vehicle.VehicleID = vehicletotransmission.VehicleID",
  "transmission": "LEFT JOIN transmission ON vehicletotransmission.TransmissionID = transmission.TransmissionID",
  "eleccontrolled": "LEFT JOIN eleccontrolled ON transmission.TransmissionElecControlledID = eleccontrolled.ElecControlledID",
  "transmissionbase": "LEFT JOIN transmissionbase ON transmission.TransmissionBaseID = transmissionbase.TransmissionBaseID",
  "transmissiontype": "LEFT JOIN transmissiontype ON transmissionbase.TransmissionTypeID = transmissiontype.TransmissionTypeID",
  "transmissioncontroltype": "LEFT JOIN transmissioncontroltype ON transmissionbase.TransmissionControlTypeID = transmissioncontroltype.TransmissionControlTypeID",
  "transmissionnumspeeds": "LEFT JOIN transmissionnumspeeds ON transmissionbase.TransmissionNumSpeedsID = transmissionnumspeeds.TransmissionNumSpeedsID",
  "mfr_transmission": "LEFT JOIN transmissionnumspeeds ON transmissionbase.TransmissionNumSpeedsID = transmissionnumspeeds.TransmissionNumSpeedsID",
  "mfr": "LEFT JOIN mfr ON transmission.TransmissionMfrID = mfr.MfrID",
  "transmissionmfrcode": "LEFT JOIN transmissionmfrcode ON transmission.TransmissionMfrCodeID = transmissionmfrcode.TransmissionMfrCodeID",
  "vehicletoengineconfig": "LEFT JOIN vehicletoengineconfig ON vehicle.VehicleID = vehicletoengineconfig.VehicleID",
  "engineconfig": "LEFT JOIN engineconfig ON vehicletoengineconfig.EngineConfigID = engineconfig.EngineConfigID",
  "ignitionsystemtype": "LEFT JOIN ignitionsystemtype ON engineconfig.IgnitionSystemTypeID = ignitionsystemtype.IgnitionSystemTypeID",
  "cylinderheadtype": "LEFT JOIN cylinderheadtype ON engineconfig.CylinderHeadTypeID = cylinderheadtype.CylinderHeadTypeID",
  "aspiration": "LEFT JOIN aspiration ON engineconfig.AspirationID = aspiration.AspirationID",
  "fueltype": "LEFT JOIN fueltype ON engineconfig.FuelTypeID = fueltype.FuelTypeID",
  "poweroutput": "LEFT JOIN poweroutput ON engineconfig.PowerOutputID = poweroutput.PowerOutputID",
  "valves": "LEFT JOIN valves ON engineconfig.ValvesID = valves.ValvesID",
  "enginevin": "LEFT JOIN enginevin ON engineconfig.EngineVINID = enginevin.EngineVINID",
  "mfr_engine": "LEFT JOIN engineversion ON engineconfig.EngineVersionID = engineversion.EngineVersionID",
  "engine_mfr": "LEFT JOIN mfr  ON engineconfig.EngineMfrID = mfr.MfrID",
  "fueldeliveryconfig": "LEFT JOIN fueldeliveryconfig ON engineconfig.FuelDeliveryConfigID = fueldeliveryconfig.FuelDeliveryConfigID",
  "fueldeliverytype": "LEFT JOIN fueldeliverytype ON fueldeliveryconfig.FuelDeliveryTypeID = fueldeliverytype.FuelDeliveryTypeID",
  "fuelsystemcontroltype": "LEFT JOIN fuelsystemcontroltype ON fueldeliveryconfig.FuelSystemControlTypeID = fuelsystemcontroltype.FuelSystemControlTypeID",
  "fueldeliverysubtype": "LEFT JOIN fueldeliverysubtype ON fueldeliveryconfig.FuelDeliverySubTypeID = fueldeliverysubtype.FuelDeliverySubTypeID",
  "fuelsystemdesign": "LEFT JOIN fuelsystemdesign ON fueldeliveryconfig.FuelSystemDesignID = fuelsystemdesign.FuelSystemDesignID",
  "enginedesignation": "LEFT JOIN enginedesignation ON engineconfig.EngineDesignationID = enginedesignation.EngineDesignationID",
  "enginebase": "LEFT JOIN enginebase ON engineconfig.EngineBaseID = enginebase.EngineBaseID",
};

export const VCDB_TABLES_PER_QUALIFIER = {
  "AspirationID": ["vehicletoengineconfig","engineconfig","aspiration"],
  "BedLengthID": ["vehicletobedconfig","bedconfig","bedlength"],
  "BedTypeID": ["vehicletobedconfig","bedconfig","bedtype"],
  "BodyNumDoorsID": ["vehicletobodystyleconfig","bodystyleconfig","bodynumdoors"],
  "BodyTypeID": ["vehicletobodystyleconfig","bodystyleconfig","bodytype"],
  "BrakeABSID": ["vehicletobrakeconfig","braketype_front","brakeabs"],
  "BrakeSystemID": ["vehicletobrakeconfig","braketype_front","brakesystem"],
  "CylinderHeadTypeID": ["vehicletoengineconfig","engineconfig","cylinderheadtype"],
  "DriveTypeID": ["vehicletodrivetype","drivetype"],
  "EngineDesignationID": ["vehicletoengineconfig","engineconfig","enginedesignation"],
  "EngineMfrID": ["vehicletoengineconfig","engineconfig","engine_mfr"],
  "EngineVersionID": ["vehicletoengineconfig","engineconfig","mfr_engine"],
  "EngineVINID": ["vehicletoengineconfig","engineconfig","enginevin"],
  "FrontBrakeTypeID": ["vehicletobrakeconfig","braketype_front","braketype"],
  "FrontSpringTypeID": ["vehicletospringtypeconfig","springtypeconfig","springtype_front","springtype"],
  "FuelDeliverySubTypeID": ["vehicletoengineconfig","engineconfig","fueldeliveryconfig","fueldeliverysubtype"],
  "FuelDeliveryTypeID": ["vehicletoengineconfig","engineconfig","fueldeliveryconfig","fueldeliverytype"],
  "FuelSystemControlTypeID": ["vehicletoengineconfig","engineconfig","fueldeliveryconfig","fuelsystemcontroltype"],
  "FuelSystemDesignID": ["vehicletoengineconfig","engineconfig","fueldeliveryconfig","fuelsystemdesign"],
  "FuelTypeID": ["vehicletoengineconfig","engineconfig","fueltype"],
  "IgnitionSystemTypeID": ["vehicletoengineconfig","engineconfig","ignitionsystemtype"],
  "MfrBodyCodeID": ["vehicletomfrbodycode","mfrbodycode"],
  "PositionID": ["positions"],
  "PowerOutputID": ["vehicletoengineconfig","engineconfig","poweroutput"],
  "RearBrakeTypeID": ["vehicletobrakeconfig","braketype_front","braketype_rear"],
  "RearSpringTypeID": ["vehicletospringtypeconfig","springtypeconfig","springtype_front","springtype_rear"],
  "RegionID": ["region"],
  "SteeringSystemID": ["vehicletosteeringconfig","steeringconfig","steeringsystem"],
  "SteeringTypeID": ["vehicletosteeringconfig","steeringconfig","steeringtype"],
  "SubModelID": ["submodel"],
  "TransElecControlledID": ["vehicletotransmission","transmission","eleccontrolled"],
  "TransmissionControlTypeID": ["vehicletotransmission","transmission","transmissionbase","transmissioncontroltype"],
  "TransmissionMfrCodeID": ["vehicletotransmission","transmission","transmissionmfrcode"],
  "TransmissionMfrID": ["vehicletotransmission","transmission","mfr"],
  "TransmissionNumSpeedsID": ["vehicletotransmission","transmission","transmissionbase","transmissionnumspeeds"],
  "TransmissionTypeID": ["vehicletotransmission","transmission","transmissionbase","transmissiontype"],
  "ValvesPerEngineID": ["vehicletoengineconfig","engineconfig","valves"],
  "WheelBaseID": ["vehicletowheelbase","wheelbase"],
};

export const VCDB_SELECTS_PER_QUALIFIER = {
  "AspirationID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',aspiration.AspirationID,'\":{\"Value\":\"',TRIM(aspiration.AspirationName),'\",\"IsQualifierInDM\":',IF(aspiration.AspirationID [CONDITION],'true','false'),'}') ORDER BY aspiration.AspirationName SEPARATOR ','),'}') AS AspirationID",
  "BedLengthID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',bedlength.BedLengthID,'\":{\"Value\":\"',CONCAT_WS(', ',CONCAT(TRIM(bedlength.BedLength),'in'),CONCAT(TRIM(bedlength.BedLengthMetric),'cm')),'\",\"IsQualifierInDM\":',IF(bedlength.BedLengthID [CONDITION],'true','false'),'}') ORDER BY bedlength.BedLength,BedLengthMetric SEPARATOR ','),'}') AS BedLengthID",
  "BedTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',bedtype.BedTypeID,'\":{\"Value\":\"',TRIM(bedtype.BedTypeName),'\",\"IsQualifierInDM\":',IF(bedtype.BedTypeID [CONDITION],'true','false'),'}') ORDER BY bedtype.BedTypeName SEPARATOR ','),'}') AS BedTypeID",
  "BodyNumDoorsID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',bodynumdoors.BodyNumDoorsID,'\":{\"Value\":\"',TRIM(bodynumdoors.BodyNumDoors),'\",\"IsQualifierInDM\":',IF(bodynumdoors.BodyNumDoorsID [CONDITION],'true','false'),'}') ORDER BY bodynumdoors.BodyNumDoors SEPARATOR ','),'}') AS BodyNumDoorsID",
  "BodyTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',bodytype.BodyTypeID,'\":{\"Value\":\"',TRIM(bodytype.BodyTypeName),'\",\"IsQualifierInDM\":',IF(bodytype.BodyTypeID [CONDITION],'true','false'),'}') ORDER BY bodytype.BodyTypeName SEPARATOR ','),'}') AS BodyTypeID",
  "BrakeABSID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',brakeabs.BrakeABSID,'\":{\"Value\":\"',TRIM(brakeabs.BrakeABSName),'\",\"IsQualifierInDM\":',IF(brakeabs.BrakeABSID [CONDITION],'true','false'),'}') ORDER BY brakeabs.BrakeABSName SEPARATOR ','),'}') AS BrakeABSID",
  "BrakeSystemID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',brakesystem.BrakeSystemID,'\":{\"Value\":\"',TRIM(brakesystem.BrakeSystemName),'\",\"IsQualifierInDM\":',IF(brakesystem.BrakeSystemID [CONDITION],'true','false'),'}') ORDER BY brakesystem.BrakeSystemName SEPARATOR ','),'}') AS BrakeSystemID",
  "CylinderHeadTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',cylinderheadtype.CylinderHeadTypeID,'\":{\"Value\":\"',TRIM(cylinderheadtype.CylinderHeadTypeName),'\",\"IsQualifierInDM\":',IF(cylinderheadtype.CylinderHeadTypeID [CONDITION],'true','false'),'}') ORDER BY cylinderheadtype.CylinderHeadTypeName SEPARATOR ','),'}') AS CylinderHeadTypeID",
  "DriveTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',drivetype.DriveTypeID,'\":{\"Value\":\"',TRIM(drivetype.DriveTypeName),'\",\"IsQualifierInDM\":',IF(drivetype.DriveTypeID [CONDITION],'true','false'),'}') ORDER BY drivetype.DriveTypeName SEPARATOR ','),'}') AS DriveTypeID",
  "EngineDesignationID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',enginedesignation.EngineDesignationID,'\":{\"Value\":\"',TRIM(enginedesignation.EngineDesignationName),'\",\"IsQualifierInDM\":',IF(enginedesignation.EngineDesignationID [CONDITION],'true','false'),'}') ORDER BY enginedesignation.EngineDesignationName SEPARATOR ','),'}') AS EngineDesignationID",
  "EngineMfrID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',mfr.MfrID,'\":{\"Value\":\"',TRIM(mfr.MfrName),'\",\"IsQualifierInDM\":',IF(mfr.MfrID [CONDITION],'true','false'),'}') ORDER BY mfr.MfrName SEPARATOR ','),'}') AS EngineMfrID",
  "EngineVersionID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',engineversion.EngineVersionID,'\":{\"Value\":\"',TRIM(engineversion.EngineVersion),'\",\"IsQualifierInDM\":',IF(engineversion.EngineVersionID [CONDITION],'true','false'),'}') ORDER BY engineversion.EngineVersion SEPARATOR ','),'}') AS EngineVersionID",
  "EngineVINID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',enginevin.EngineVINID,'\":{\"Value\":\"',TRIM(enginevin.EngineVINName),'\",\"IsQualifierInDM\":',IF(enginevin.EngineVINID [CONDITION],'true','false'),'}') ORDER BY enginevin.EngineVINName SEPARATOR ','),'}') AS EngineVINID",
  "FrontBrakeTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',braketype_front.BrakeTypeID,'\":{\"Value\":\"',TRIM(braketype_front.BrakeTypeName),'\",\"IsQualifierInDM\":',IF(braketype_front.BrakeTypeID [CONDITION],'true','false'),'}') ORDER BY braketype_front.BrakeTypeName SEPARATOR ','),'}') AS FrontBrakeTypeID",
  "FrontSpringTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',springtype_front.SpringTypeID,'\":{\"Value\":\"',TRIM(springtype_front.SpringTypeName),'\",\"IsQualifierInDM\":',IF(springtype_front.SpringTypeID [CONDITION],'true','false'),'}') ORDER BY springtype_front.SpringTypeName SEPARATOR ','),'}') AS FrontSpringTypeID",
  "FuelDeliverySubTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',fueldeliverysubtype.FuelDeliverySubTypeID,'\":{\"Value\":\"',TRIM(fueldeliverysubtype.FuelDeliverySubTypeName),'\",\"IsQualifierInDM\":',IF(fueldeliverysubtype.FuelDeliverySubTypeID [CONDITION],'true','false'),'}') ORDER BY fueldeliverysubtype.FuelDeliverySubTypeName SEPARATOR ','),'}') AS FuelDeliverySubTypeID",
  "FuelDeliveryTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',fueldeliverytype.FuelDeliveryTypeID,'\":{\"Value\":\"',TRIM(fueldeliverytype.FuelDeliveryTypeName),'\",\"IsQualifierInDM\":',IF(fueldeliverytype.FuelDeliveryTypeID [CONDITION],'true','false'),'}') ORDER BY fueldeliverytype.FuelDeliveryTypeName SEPARATOR ','),'}') AS FuelDeliveryTypeID",
  "FuelSystemControlTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',fuelsystemcontroltype.FuelSystemControlTypeID,'\":{\"Value\":\"',TRIM(fuelsystemcontroltype.FuelSystemControlTypeName),'\",\"IsQualifierInDM\":',IF(fuelsystemcontroltype.FuelSystemControlTypeID [CONDITION],'true','false'),'}') ORDER BY fuelsystemcontroltype.FuelSystemControlTypeName SEPARATOR ','),'}') AS FuelSystemControlTypeID",
  "FuelSystemDesignID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',fuelsystemdesign.FuelSystemDesignID,'\":{\"Value\":\"',TRIM(fuelsystemdesign.FuelSystemDesignName),'\",\"IsQualifierInDM\":',IF(fuelsystemdesign.FuelSystemDesignID [CONDITION],'true','false'),'}') ORDER BY fuelsystemdesign.FuelSystemDesignName SEPARATOR ','),'}') AS FuelSystemDesignID",
  "FuelTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',fueltype.FuelTypeID,'\":{\"Value\":\"',TRIM(fueltype.FuelTypeName),'\",\"IsQualifierInDM\":',IF(fueltype.FuelTypeID [CONDITION],'true','false'),'}') ORDER BY fueltype.FuelTypeName SEPARATOR ','),'}') AS FuelTypeID",
  "IgnitionSystemTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',ignitionsystemtype.IgnitionSystemTypeID,'\":{\"Value\":\"',TRIM(ignitionsystemtype.IgnitionSystemTypeName),'\",\"IsQualifierInDM\":',IF(ignitionsystemtype.IgnitionSystemTypeID [CONDITION],'true','false'),'}') ORDER BY ignitionsystemtype.IgnitionSystemTypeName SEPARATOR ','),'}') AS IgnitionSystemTypeID",
  "MfrBodyCodeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',mfrbodycode.MfrBodyCodeID,'\":{\"Value\":\"',TRIM(mfrbodycode.MfrBodyCodeName),'\",\"IsQualifierInDM\":',IF(mfrbodycode.MfrBodyCodeID [CONDITION],'true','false'),'}') ORDER BY mfrbodycode.MfrBodyCodeName SEPARATOR ','),'}') AS MfrBodyCodeID",
  "PositionID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',positions.PositionID,'\":{\"Value\":\"',TRIM(positions.Position),'\",\"IsQualifierInDM\":',IF(positions.PositionID [CONDITION],'true','false'),'}') ORDER BY positions.Position SEPARATOR ','),'}') AS PositionID",
  "PowerOutputID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',poweroutput.PowerOutputID,'\":{\"Value\":\"',CONCAT_WS(', ',CONCAT(TRIM(poweroutput.HorserPower),'HP'),CONCAT(TRIM(poweroutput.KilowattPower),'kW')),'\",\"IsQualifierInDM\":',IF(poweroutput.PowerOutputID [CONDITION],'true','false'),'}') ORDER BY poweroutput.HorsePower,KilowattPower SEPARATOR ','),'}') AS PowerOutputID",
  "RearBrakeTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',braketype_rear.BrakeTypeID,'\":{\"Value\":\"',TRIM(braketype_rear.BrakeTypeName),'\",\"IsQualifierInDM\":',IF(braketype_rear.BrakeTypeID [CONDITION],'true','false'),'}') ORDER BY braketype_rear.BrakeTypeName SEPARATOR ','),'}') AS RearBrakeTypeID",
  "RearSpringTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',springtype_rear.SpringTypeID,'\":{\"Value\":\"',TRIM(springtype_rear.SpringTypeName),'\",\"IsQualifierInDM\":',IF(springtype_rear.SpringTypeID [CONDITION],'true','false'),'}') ORDER BY springtype_rear.SpringTypeName SEPARATOR ','),'}') AS RearSpringTypeID",
  "RegionID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',region.RegionID,'\":{\"Value\":\"',TRIM(region.RegionName),'\",\"IsQualifierInDM\":',IF(region.RegionID [CONDITION],'true','false'),'}') ORDER BY region.RegionAbbr,RegionName SEPARATOR ','),'}') AS RegionID",
  "SteeringSystemID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',steeringsystem.SteeringSystemID,'\":{\"Value\":\"',TRIM(steeringsystem.SteeringSystemName),'\",\"IsQualifierInDM\":',IF(steeringsystem.SteeringSystemID [CONDITION],'true','false'),'}') ORDER BY steeringsystem.SteeringSystemName SEPARATOR ','),'}') AS SteeringSystemID",
  "SteeringTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',steeringtype.SteeringTypeID,'\":{\"Value\":\"',TRIM(steeringtype.SteeringTypeName),'\",\"IsQualifierInDM\":',IF(steeringtype.SteeringTypeID [CONDITION],'true','false'),'}') ORDER BY steeringtype.SteeringTypeName SEPARATOR ','),'}') AS SteeringTypeID",
  "SubModelID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',submodel.SubModelID,'\":{\"Value\":\"',TRIM(submodel.SubModelName),'\",\"IsQualifierInDM\":',IF(submodel.SubModelID [CONDITION],'true','false'),'}') ORDER BY submodel.SubModelName SEPARATOR ','),'}') AS SubModelID",
  "TransElecControlledID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',eleccontrolled.ElecControlledID,'\":{\"Value\":\"',TRIM(eleccontrolled.ElecControlled),'\",\"IsQualifierInDM\":',IF(eleccontrolled.ElecControlledID [CONDITION],'true','false'),'}') ORDER BY eleccontrolled.ElecControlled SEPARATOR ','),'}') AS TransElecControlledID",
  "TransmissionControlTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',transmissioncontroltype.TransmissionControlTypeID,'\":{\"Value\":\"',TRIM(transmissioncontroltype.TransmissionControlTypeName),'\",\"IsQualifierInDM\":',IF(transmissioncontroltype.TransmissionControlTypeID [CONDITION],'true','false'),'}') ORDER BY transmissioncontroltype.TransmissionControlTypeName SEPARATOR ','),'}') AS TransmissionControlTypeID",
  "TransmissionMfrCodeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',transmissionmfrcode.TransmissionMfrCodeID,'\":{\"Value\":\"',TRIM(transmissionmfrcode.TransmissionMfrCode),'\",\"IsQualifierInDM\":',IF(transmissionmfrcode.TransmissionMfrCodeID [CONDITION],'true','false'),'}') ORDER BY transmissionmfrcode.TransmissionMfrCode SEPARATOR ','),'}') AS TransmissionMfrCodeID",
  "TransmissionMfrID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',mfr.MfrID,'\":{\"Value\":\"',TRIM(mfr.MfrName),'\",\"IsQualifierInDM\":',IF(mfr.MfrID [CONDITION],'true','false'),'}') ORDER BY mfr.MfrName SEPARATOR ','),'}') AS TransmissionMfrID",
  "TransmissionNumSpeedsID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',transmissionnumspeeds.TransmissionNumSpeedsID,'\":{\"Value\":\"',TRIM(transmissionnumspeeds.TransmissionNumSpeeds),'\",\"IsQualifierInDM\":',IF(transmissionnumspeeds.TransmissionNumSpeedsID [CONDITION],'true','false'),'}') ORDER BY transmissionnumspeeds.TransmissionNumSpeeds SEPARATOR ','),'}') AS TransmissionNumSpeedsID",
  "TransmissionTypeID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',transmissiontype.TransmissionTypeID,'\":{\"Value\":\"',TRIM(transmissiontype.TransmissionTypeName),'\",\"IsQualifierInDM\":',IF(transmissiontype.TransmissionTypeID [CONDITION],'true','false'),'}') ORDER BY transmissiontype.TransmissionTypeName SEPARATOR ','),'}') AS TransmissionTypeID",
  "ValvesPerEngineID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',valves.ValvesID,'\":{\"Value\":\"',TRIM(valves.ValvesPerEngine),'\",\"IsQualifierInDM\":',IF(valves.ValvesID [CONDITION],'true','false'),'}') ORDER BY valves.ValvesPerEngine SEPARATOR ','),'}') AS ValvesPerEngineID",
  "WheelBaseID": "CONCAT('{',GROUP_CONCAT(DISTINCT CONCAT('\"',wheelbase.WheelBaseID,'\":{\"Value\":\"',CONCAT_WS(', ',CONCAT(TRIM(wheelbase.WheelBase),'in'),CONCAT(TRIM(wheelbase.WheelBaseMetric),'cm')),'\",\"IsQualifierInDM\":',IF(wheelbase.WheelBaseID [CONDITION],'true','false'),'}') ORDER BY wheelbase.WheelBase,WheelBaseMetric SEPARATOR ','),'}') AS WheelBaseID",
};
